[project]
name = ""
version = "0.0.1"
requires-python = ">=3.10,<4"
dependencies = ["davidkhala-utils"]

[dependency-groups]
dev = ["pytest"]

[tool.uv]
package = false

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
